// calculadora/src/main/Calculator.jsx
import React, { useState } from 'react'

import Button from '../Components/Button'
import Display from '../Components/Display'

import './Calculator.css'

export default function Calculator() {
    const [ displayValue, setDisplayValue ] = useState('0')
    const [ clearDisplay, setClearDisplay ] = useState(false)
    const [ operationState, setOperationState ] = useState(null)
    const [ values, setValues ] = useState([0, 0])
    const [ current, setCurrent ] = useState(0)

    function doOperation(operation, value1, value2) {
        switch (operation) {
            case '+':
                return value1 + value2
            case '-':
                    return value1 - value2
            case '*':
                    return value1 * value2
            case '/':
                    return value1 / value2
            default:
                return null
        }
    }

    function clearMemory() {
        setDisplayValue('0')
        setClearDisplay(false)
        setOperationState(null)
        setValues([0, 0])
        setCurrent(0)
    }

    function setOperation(operation) {
        if (current === 0) {
            setOperationState(operation)
            setCurrent(1)
            setClearDisplay(true)
        } else {
            const done = operation === '='
            
            const localValues = values
            localValues[0] = doOperation(operationState, localValues[0], localValues[1])
            localValues[1] = 0

            setDisplayValue(localValues[0].toString())
            setOperationState(done ? null : operation)
            setCurrent(done ? 0 : 1)
            setClearDisplay(!done)
            setValues(localValues)
        }
    }

    function addDigit(digit) {
        if (digit === '.' && displayValue.includes('.')) {
            return
        }

        const clearDisplayState = displayValue === '0' || clearDisplay
        const currentValue = clearDisplayState ? '' : displayValue
        const displayValueState = currentValue + digit
        setDisplayValue(displayValueState.toString())
        setClearDisplay(false)

        if(digit !== '.') {
            const i = current
            const newValue = parseFloat(displayValueState)
            const newArrValues = values
            newArrValues[i] = newValue
            setValues(newArrValues)
        }
    }

    return (
        <div className="calculator">
            <Display value={displayValue}/>
            <Button label="AC" click={() => clearMemory()} triple />
            <Button label="/" click={(operation) => setOperation(operation)} operation />
            <Button label="7" click={(digit) => addDigit(digit)} />
            <Button label="8" click={(digit) => addDigit(digit)} />
            <Button label="9" click={(digit) => addDigit(digit)} />
            <Button label="*" click={(operation) => setOperation(operation)} operation />
            <Button label="4" click={(digit) => addDigit(digit)} />
            <Button label="5" click={(digit) => addDigit(digit)} />
            <Button label="6" click={(digit) => addDigit(digit)} />
            <Button label="-" click={(operation) => setOperation(operation)} operation />
            <Button label="1" click={(digit) => addDigit(digit)} />
            <Button label="2" click={(digit) => addDigit(digit)} />
            <Button label="3" click={(digit) => addDigit(digit)} />
            <Button label="+" click={(operation) => setOperation(operation)} operation />
            <Button label="0" click={(digit) => addDigit(digit)} double />
            <Button label="." click={(digit) => addDigit(digit)} />
            <Button label="=" click={(operation) => setOperation(operation)} operation />
        </div>
    )
}

// calculadora-vue/src/main/Calculator.vue
<template>
  <div class="calculator">
    <Display :value="displayValue" />
    <Button label="AC" triple @onClick="clearMemory" />
    <Button label="/" operation @onClick="setOperation" />
    <Button label="7" @onClick="addDigit" />
    <Button label="8" @onClick="addDigit" />
    <Button label="9" @onClick="addDigit" />
    <Button label="*" operation @onClick="setOperation" />
    <Button label="4" @onClick="addDigit" />
    <Button label="5" @onClick="addDigit" />
    <Button label="6" @onClick="addDigit" />
    <Button label="-" operation @onClick="setOperation" />
    <Button label="1" @onClick="addDigit" />
    <Button label="2" @onClick="addDigit" />
    <Button label="3" @onClick="addDigit" />
    <Button label="+" operation @onClick="setOperation" />
    <Button label="0" double @onClick="addDigit" />
    <Button label="." @onClick="addDigit" />
    <Button label="=" operation @onClick="setOperation" />
  </div>
</template>

<script>
import Button from '../components/Button'
import Display from '../components/Display'

export default {
    data: function() {
        return {
            displayValue: '0',
            clearDisplay: false,
            operation: null,
            values: [0, 0],
            current: 0
        }
    },
    components: {
        Button,
        Display
    },
    methods: {
        clearMemory() {
            Object.assign(this.$data, this.$options.data())
        },
        setOperation(operation) {
            if (this.current === 0) {
                this.operation = operation
                this.current = 1
                this.clearDisplay = true
            } else {
                const equals = operation === "="
                const currentOperation = this.operation

                try {
                    this.values[0] = eval(
                        `${this.values[0]} ${currentOperation} ${this.values[1]}`
                    )
                } catch (e) {
                    this.$emit('onError', e)
                }

                this.values[1] = 0

                this.displayValue = this.values[0]
                this.operation = equals ? null : operation
                this.current = equals ? 0 : 1
                this.clearDisplay = !equals
            }
        },
        addDigit(digit) {
            if ( digit === '.' && this.displayValue.includes('.')) {
                return
            }

            const clearDisplay = this.displayValue === '0'
                || this.clearDisplay
            const currentValue = clearDisplay ? "" : this.displayValue
            const displayValue = currentValue + digit

            this.displayValue = displayValue
            this.clearDisplay = false
            this.values[this.current] = displayValue
        }
    }
}
</script>

<style>
.calculator {
    height: 320px;
    width: 235px;
    border-radius: 5px;
    overflow: hidden;

    display: grid;
    grid-template-columns: repeat(4, 25%);
    grid-template-rows: 1fr 48px 48px 48px 48px 48px;
}
</style>
